/* 
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.7
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;
using System.Net;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoreApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StoreApiTests
    {
        // private readonly string baseUrl = "http://localhost:8080/api/v3";
        private readonly string baseUrl = "https://petstore.swagger.io/v2";
        private StoreApi instance;
        private RestClient client;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StoreApi(baseUrl);
            client = new RestClient(baseUrl);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
            client = null;
            instance = null;
        }

        /// <summary>
        /// Test an instance of StoreApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StoreApi
            //Assert.IsInstanceOfType(typeof(StoreApi), instance, "instance is a StoreApi");
        }

        [Test]
        public void GetInventory_ShouldReturnDictionary()
        {
            var request = new RestRequest("store/inventory", Method.GET);
            var response = client.Execute<Dictionary<string, int>>(request);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
        }

        [Test]
        public void PlaceOrder_Valid_ShouldReturnOrder()
        {
            var request = new RestRequest("store/order", Method.POST);
            var order = new
            {
                id = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            };

            request.AddJsonBody(order);
            var response = client.Execute<Order>(request);

            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void PlaceOrder_Invalid_ShouldReturnOrder()
        {
            var request = new RestRequest("store/order", Method.POST);
            var order = new
            {
                id = "abc",
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            }; // construct wrong id in order to place an order for a pet

            request.AddJsonBody(order);
            var response = client.Execute<Order>(request);

            Assert.AreEqual(HttpStatusCode.BadRequest, response.StatusCode);
        }

        [Test]
        public void GetOrderById_Valid_ShouldReturnOrder()
        {
            long orderId = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            var createRequest = new RestRequest("store/order", Method.POST);
            createRequest.AddJsonBody(new
            {
                id = orderId,
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            });

            var createResponse = client.Execute(createRequest);
            Assert.AreEqual(HttpStatusCode.OK, createResponse.StatusCode, "Order creation failed.");
            
            var getRequest = new RestRequest($"store/order/{orderId}", Method.GET);
            var getResponse = client.Execute<Order>(getRequest);

            Assert.AreEqual(HttpStatusCode.OK, getResponse.StatusCode);
        }

        [Test]
        public void GetOrderById_DifferentId_ShouldReturnNotFound()
        {
            long orderId = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            var createRequest = new RestRequest("store/order", Method.POST);
            createRequest.AddJsonBody(new
            {
                id = 2,
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            });

            var createResponse = client.Execute(createRequest);
            Assert.AreEqual(HttpStatusCode.OK, createResponse.StatusCode, "Order creation failed.");

            var getRequest = new RestRequest($"store/order/{orderId}", Method.GET);
            var getResponse = client.Execute<Order>(getRequest);

            Assert.AreEqual(HttpStatusCode.NotFound, getResponse.StatusCode);
        }

        [Test]
        public void GetOrderById_InvalidId_ShouldReturnBadRequest()
        {
            long orderId = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            var createRequest = new RestRequest("store/order", Method.POST);
            createRequest.AddJsonBody(new
            {
                id = "aaaa",
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            });

            var createResponse = client.Execute(createRequest);
            Assert.AreEqual(HttpStatusCode.BadRequest, createResponse.StatusCode, "Order creation failed.");

            var getRequest = new RestRequest($"store/order/aaaa", Method.GET);
            var getResponse = client.Execute<Order>(getRequest);

            Assert.AreEqual(HttpStatusCode.BadRequest, getResponse.StatusCode);
        }

        [Test]
        public void DeleteOrder_Valid_ShouldReturnOk()
        {
            long orderId = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            var createRequest = new RestRequest("store/order", Method.POST);
            createRequest.AddJsonBody(new
            {
                id = orderId,
                petId = 1,
                quantity = 1,
                shipDate = DateTime.UtcNow.ToString("o"),
                status = "placed",
                complete = true
            });

            var createResponse = client.Execute(createRequest);
            Assert.AreEqual(HttpStatusCode.OK, createResponse.StatusCode, "Order creation failed.");

            var deleteRequest = new RestRequest($"store/order/{orderId}", Method.DELETE);
            var deleteResponse = client.Execute(deleteRequest);

            Assert.AreEqual(HttpStatusCode.OK, deleteResponse.StatusCode);
        }

        [Test]
        public void DeleteOrder_InvalidId_ShouldReturnOk()
        {
            long orderId = -99999;
            var deleteRequest = new RestRequest($"store/order/{orderId}", Method.DELETE);
            var deleteResponse = client.Execute(deleteRequest);

            Assert.AreEqual(HttpStatusCode.OK, deleteResponse.StatusCode);
        }

        /// <summary>
        /// Test DeleteOrder
        /// </summary>
        [Test]
        public void DeleteOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? orderId = null;
            //instance.DeleteOrder(orderId);
            
        }
        
        /// <summary>
        /// Test GetInventory
        /// </summary>
        [Test]
        public void GetInventoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetInventory();
            //Assert.IsInstanceOf<Dictionary<string, int?>> (response, "response is Dictionary<string, int?>");
        }
        
        /// <summary>
        /// Test GetOrderById
        /// </summary>
        [Test]
        public void GetOrderByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? orderId = null;
            //var response = instance.GetOrderById(orderId);
            //Assert.IsInstanceOf<Order> (response, "response is Order");
        }
        
        /// <summary>
        /// Test PlaceOrder
        /// </summary>
        [Test]
        public void PlaceOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Order body = null;
            //var response = instance.PlaceOrder(body);
            //Assert.IsInstanceOf<Order> (response, "response is Order");
        }
        
    }

}
