/* 
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.7
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;
using System.Net;
using System.Text.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserApiTests
    {
        // private readonly string baseUrl = "http://localhost:8080/api/v3";
        private readonly string baseUrl = "https://petstore.swagger.io/v2";
        private UserApi instance;
        private RestClient client;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserApi();
            client = new RestClient(baseUrl);
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {
            client = null;
            instance = null;
        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserApi
            //Assert.IsInstanceOfType(typeof(UserApi), instance, "instance is a UserApi");
        }


        /// <summary>
        /// Test CreateUser
        /// </summary>
        [Test]
        public void CreateUser_Valid_Test()
        {
            var newUser = new
            {
                id = 1,
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var request = new RestRequest("user", Method.POST);
            request.AddJsonBody(newUser);
            var response = client.Execute(request);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
        }

        [Test]
        public void GetUserByUsername_Valid_ShouldReturnUser()
        {
            var newUser = new
            {
                id = 1,
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var requestCreate = new RestRequest("user", Method.POST);
            requestCreate.AddJsonBody(newUser);
            var responseCreate = client.Execute(requestCreate);
            Assert.AreEqual(responseCreate.StatusCode, HttpStatusCode.OK);
            // Now retrieve the user
            var requestGet = new RestRequest("user/testuser", Method.GET);
            var response = client.Execute<User>(requestGet);
            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var user = JsonSerializer.Deserialize<User>(response.Content, options);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
            Assert.AreEqual("testuser", user.Username);
        }

        [Test]
        public void GetUserByUsername_Invalid_ShouldReturn400()
        {
            var newUser = new
            {
                id = 1,
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var requestCreate = new RestRequest("user", Method.POST);
            requestCreate.AddJsonBody(newUser);
            var responseCreate = client.Execute(requestCreate);
            Assert.AreEqual(responseCreate.StatusCode, HttpStatusCode.OK);
            // Now retrieve the user
            var invalidUsername = Uri.EscapeDataString("#$%#");
            var requestGet = new RestRequest($"user/{invalidUsername}", Method.GET);
            var response = client.Execute<User>(requestGet);

            Assert.IsTrue(
            response.StatusCode == HttpStatusCode.NotFound ||
            response.StatusCode == HttpStatusCode.BadRequest,
                $"Expected 400 or 404 but got {response.StatusCode}");

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                var user = JsonSerializer.Deserialize<User>(response.Content, options);
                Assert.AreEqual("testuser", user.Username);
            }
        }

        [Test]
        public void GetUserByUsername_DifferentId_ShouldReturn400()
        {
            var newUser = new
            {
                id = 1,
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var requestCreate = new RestRequest("user", Method.POST);
            requestCreate.AddJsonBody(newUser);
            var responseCreate = client.Execute(requestCreate);
            Assert.AreEqual(responseCreate.StatusCode, HttpStatusCode.OK);
            // Now retrieve the user
            var invalidUsername = Uri.EscapeDataString("-999");
            var requestGet = new RestRequest($"user/{invalidUsername}", Method.GET);
            var response = client.Execute<User>(requestGet);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.NotFound);
        }

        [Test]
        public void CreateListUser_ShouldBeSuccessful()
        {
            var newUser1 = new
            {
                id = 1,
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var newUser2 = new
            {
                id = 2,
                username = "testuser2",
                firstName = "Test2",
                lastName = "User2",
                email = "test2@user.com",
                password = "password2",
                phone = "1234567890",
                userStatus = 1
            };
            List<object> users = new List<object> { newUser1, newUser2 };
            var request = new RestRequest("user/createWithList", Method.POST);
            request.AddJsonBody(users);
            var response = client.Execute(request);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
        }

        [Test]
        public void CreateListUser_WithInvalidUser_ShouldBeUnsuccessful()
        {
            var newUser1 = new
            {
                id = "aaa",
                username = "testuser",
                firstName = "Test",
                lastName = "User",
                email = "test@user.com",
                password = "password",
                phone = "1234567890",
                userStatus = 1
            };
            var newUser2 = new
            {
                id = "bbb",
                username = "testuser2",
                firstName = "Test2",
                lastName = "User2",
                email = "test2@user.com",
                password = "password2",
                phone = "1234567890",
                userStatus = 1
            };
            List<object> users = new List<object> { newUser1, newUser2 };
            var request = new RestRequest("user/createWithList", Method.POST);
            request.AddJsonBody(users);
            var response = client.Execute(request);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.BadRequest);
        }

        [Test]
        public void CreateUsersWithList_ShouldReturn200()
        {
            var users = new[]
            {
                new { id = 4, username = "listuser1", firstName = "List", lastName = "User1", email = "l1@test.com", password = "pass", phone = "222", userStatus = 0 },
                new { id = 5, username = "listuser2", firstName = "List", lastName = "User2", email = "l2@test.com", password = "pass", phone = "333", userStatus = 1 }
            };
            var request = new RestRequest("user/createWithList", Method.POST).AddJsonBody(users);
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void LoginUser_Valid_ShouldReturn200()
        {
            var request = new RestRequest("user/login", Method.GET);
            request.AddParameter("username", "testuser");
            request.AddParameter("password", "password");
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void LoginUser_Invalid_ShouldReturn400()
        {
            var request = new RestRequest("user/login", Method.GET);
            request.AddParameter("username", "invaliduser");
            request.AddParameter("password", "invalidpassword");
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void LogoutUser_ShouldReturn200()
        {
            var request = new RestRequest("user/logout", Method.GET);
            request.AddParameter("username", "testuser");
            request.AddParameter("password", "password");
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void DeleteUser_Valid_ShouldReturn200()
        {
            var request = new RestRequest("user/testuser", Method.DELETE);
            request.AddParameter("username", "testuser");
            request.AddParameter("password", "password");
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void DeleteUser_Invalid_ShouldReturn400()
        {
            var request = new RestRequest("user/invaliduser", Method.DELETE);
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void DeleteUser_DifferentUser_ShouldReturn400()
        {
            var request = new RestRequest("user/asdfasdf", Method.DELETE);
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void UpdateUser_Valid_ShouldReturn200()
        {
            var request = new RestRequest("user/testuser", Method.PUT);
            var newUser10 = new
            {
                id = 10,
                username = "testnew",
                firstName = "Testnew",
                lastName = "Usernew",
                email = "test10@user.com",
                password = "password10",
                phone = "1234567890",
                userStatus = 1
            };
            request.AddJsonBody(newUser10);
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        }

        [Test]
        public void UpdateUser_Invalid_ShouldReturn400()
        {
            var request = new RestRequest("user/testuser", Method.PUT);
            var newUser11 = new
            {
                id = "aaa",
                username = "testnew",
                firstName = "Testnew",
                lastName = "Usernew",
                email = "test10@user.com",
                password = "password10",
                phone = "1234567890",
                userStatus = 1
            };
            request.AddJsonBody(newUser11);
            var response = client.Execute(request);
            Assert.AreEqual(HttpStatusCode.BadRequest, response.StatusCode);
        }

        [Test]
        public void UpdateUser_UserNotFound_ShouldReturn404()
        {
            var request = new RestRequest("user/xyz", Method.PUT);
            var newUser11 = new
            {
                id = "aaa",
                username = "testnew",
                firstName = "Testnew",
                lastName = "Usernew",
                email = "test10@user.com",
                password = "password10",
                phone = "1234567890",
                userStatus = 1
            };
            request.AddJsonBody(newUser11);
            var response = client.Execute(request);
            Assert.IsTrue(
               response.StatusCode == HttpStatusCode.NotFound ||
               response.StatusCode == HttpStatusCode.BadRequest,
                   $"Expected 400 or 404 but got {response.StatusCode}");
        }
        /// <summary>
        /// Test CreateUsersWithArrayInput
        /// </summary>
        [Test]
        public void CreateUsersWithArrayInputTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<User> body = null;
            //instance.CreateUsersWithArrayInput(body);
            
        }
        
        /// <summary>
        /// Test CreateUsersWithListInput
        /// </summary>
        [Test]
        public void CreateUsersWithListInputTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<User> body = null;
            //instance.CreateUsersWithListInput(body);
            
        }
        
        /// <summary>
        /// Test DeleteUser
        /// </summary>
        [Test]
        public void DeleteUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //instance.DeleteUser(username);
            
        }
        
        /// <summary>
        /// Test GetUserByName
        /// </summary>
        [Test]
        public void GetUserByNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetUserByName(username);
            //Assert.IsInstanceOf<User> (response, "response is User");
        }
        
        /// <summary>
        /// Test LoginUser
        /// </summary>
        [Test]
        public void LoginUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //string password = null;
            //var response = instance.LoginUser(username, password);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test LogoutUser
        /// </summary>
        [Test]
        public void LogoutUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.LogoutUser();
            
        }
        
        /// <summary>
        /// Test UpdateUser
        /// </summary>
        [Test]
        public void UpdateUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //User body = null;
            //instance.UpdateUser(username, body);
            
        }
        
    }

}
